#!/usr/bin/python
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
import json
import commands
import subprocess
import sys
import os

dest = sys.argv[1]
days = sys.argv[2]
timestamp = commands.getstatusoutput('date --rfc-3339=date')[1]
doMove = False

with open('/tmp/TO-restore-file-list', 'r') as data_file:
    data = json.load(data_file)
subprocess.call(["/bin/rm", "-rf", "/tmp/TO-restore-file-list"])

args = []
args.append("/sbin/e-smith/restore-file")

if (int(days) > 0):
   args.append('-t ' + str(days));

if(dest == "/"):
    args.append("/")
else:
    doMove = True
    args.append("/tmp/restored_" + str(timestamp))

for it in data:
    args.append(it)

devnull = open(os.devnull, 'w')
# exec restore
try:
    subprocess.call(args, stdout=devnull)
except:
    print "ERROR"
    sys.exit(1)

# move dir
if(doMove):
    for it in data:
        dest =  str(it) + "_" + str(timestamp)
        subprocess.call(["/bin/rm", "-rf", dest], stderr=devnull)
        subprocess.call(["/bin/mv", "-f", "/tmp/restored_" + str(timestamp) + str(it), dest], stderr=devnull)
        print str(it) + "_" + str(timestamp)

    subprocess.call(["/bin/rm", "-rf", "/tmp/restored_" + str(timestamp)])
