#!/bin/bash
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
DEST=$1
shift
FILE=$(echo $@ | sed -e 's/%20/\\ /g')

TIMESTAMP=`date --rfc-3339=date`

if [ "$DEST" == "/" ]; then
    /sbin/e-smith/restore-file / $FILE
    echo "/"
else
	#echo "/sbin/e-smith/restore-file /tmp/restored_${TIMESTAMP} $FILE"
	/sbin/e-smith/restore-file "/tmp/restored_${TIMESTAMP}" $FILE
	for F in $FILE ; do
		if [ "$(ls -A /tmp/restored_${TIMESTAMP}${F})" ]; then
			/bin/mv "/tmp/restored_${TIMESTAMP}${F}" "${F}_${TIMESTAMP}"
	    	echo "${F}_${TIMESTAMP}"
		fi
	done
	/bin/rm -rf "/tmp/restored_${TIMESTAMP}"
fi
