#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# get backup type
TYPE=$(/sbin/e-smith/db backups gettype backup-data)

if [ "${TYPE}" = "duplicity" ] || [ "${TYPE}" = "restic" ]; then
    COD=$(/sbin/e-smith/db backups getprop backup-data CleanupOlderThan)
    if [[ $COD == 'never' ]]; then
        exit 0
    fi

    COD=$(($(echo $COD | sed 's/D$//')-1))

    /usr/bin/find /var/cache/restore/ -name "duc-*.xml" -ctime +$COD -exec /bin/rm {} \;
fi

if [ "${TYPE}" = "rsync" ]; then
    # get backup VFSType
    vfs=$(/sbin/e-smith/db backups getprop backup-data VFSType)

    # mount rsync directory
    /etc/e-smith/events/actions/mount-${vfs} fake-event backup-data

    # get current files lists
    for b in $(/usr/bin/find /var/cache/restore/duc-*); do
        duc_timestamp=$(/usr/bin/echo ${b} | /usr/bin/cut -d '-' -f2 | /usr/bin/cut -d '.' -f1)
        backup_rsync_date=$(/usr/bin/date -d @${duc_timestamp} +%Y-%m-%d)

        # list files inside mounted directory
        results=$(/usr/bin/find /mnt/backup-backup-data/$(/usr/bin/hostname -s)/${backup_rsync_date}* -maxdepth 1 -mindepth 1 2>/dev/null)

        # if $results list is empty, rsync backup is not present, delete it
        if [ "x${results}" = "x" ]; then
            /usr/bin/rm -rf ${b}
        fi
    done

    # umount rsync directory
    /etc/e-smith/events/actions/umount-${vfs} fake-event backup-data

fi

exit 0
