#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# convert backup list into array
mapfile -t BACKUPS < <( /sbin/e-smith/db backups keys )

# loop in restore data list directory
for b in /var/lib/nethserver/backup/restore/*; do
    BACKUP_PATH=$(/usr/bin/echo ${b} | /usr/bin/cut -d '@' -f1)
    BACKUP_NAME=$(/usr/bin/basename ${BACKUP_PATH})

    # if there is a backup data list, but the backup doesn't exists, remove it
    if [[ ! " ${BACKUPS[@]} " =~ " ${BACKUP_NAME} " ]]; then
        /usr/bin/rm -f ${b}
    fi
done