#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use NethServer::ApiTools;
use JSON qw(encode_json decode_json);
use POSIX qw(strftime);

my $input = NethServer::ApiTools::readInput();
my $output = {};

my $action = $input->{'action'};

if ($action eq 'list-files') {
    my $backup = $input->{'backup'};
    my $date = $input->{'date'};
    my $string = $input->{'string'};

    $output = `/usr/bin/zcat /var/lib/nethserver/backup/restore/$backup-$date.gz | /usr/bin/egrep -i \"$string\" | /usr/libexec/nethserver/api/nethserver-restore-data/filenames2json`;
    print $output;

} elsif ($action eq 'restore-files') {
    my $backup = $input->{'backup'};
    my $date = $input->{'date'};
    my $files = $input->{'files'};
    my $override = $input->{'override'};

    # check if engine is restic
    my $type = `/sbin/e-smith/db backups gettype $backup`;
    chomp($type);
    if ($type eq 'restic') {
        my $datestring = strftime "%Y%m%d%H%M%S", localtime($date);
        my $logfile = "/var/log/backup/backup-$backup-$datestring.log";
        $date = `/usr/bin/egrep 'snapshot (.*) saved' $logfile | awk '{print $2'}`;
    }

    for my $file (@$files) {
        my $datestring = strftime "%Y%m%d-%H:%M:%S", localtime;
        my $filepath = $override ? '/' : "$file-backup-$datestring";
        `/sbin/e-smith/restore-file -b $backup -t $date $filepath $file`;
    }
} else {
    NethServer::ApiTools::error();
}
