#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
backup=$1
log=$2 # not used
exit_code=$3 # not used
epoch=$4

type=$(/sbin/e-smith/db backups gettype $backup)
filter="/usr/bin/tee"

if [ "$type" = "duplicity" ]; then
    filter="/usr/bin/sed -e 's/[0-9]\{8\}T[0-9]\{6\}Z /\//'"
fi

if [ "$type" = "rsync" ]; then
    filter="/usr/bin/sed -e 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-[0-9]\{6\}\///'"
fi

/sbin/e-smith/backup-data-list -b $backup -f | eval $filter | /usr/bin/gzip -9 > "/var/lib/nethserver/backup/restore/$backup-$epoch.gz"